version: '3'
services:

  #MySQL用コンテナ
  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysq
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test

  #phpMyAdmin用コンテナ
  phpmyadmin:
    container_name: phpMyAdmin
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    restart: always
    ports:
      - "88:88"

  #php用コンテナ
  php:
    container_name: php-apache
    build: ./php
    volumes:
      - ./html:/var/www/html
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mysql
    environment:
      - TZ=Asia/Tokyo
      - APACHE_DOCUMENT_ROOT=/var/www/html/
      - APP_DOMAIN=localhost
